spring:
  datasource:
    url: jdbc:localhost:3306/banma_dev
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.github.java.domain
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    call-setters-on-nulls: true

